/*
 * hmi.c
 *
 * Created: Apr 2021
 * Author: Arjan te Marvelde
 * 
 * This file contains the HMI driver, processing user inputs.
 * It will also do the logic behind these, and write feedback to the LCD.
 *
 * *** MMI controls ***
 *
 * The 4 buttons have the following functions (GP_BTN_x):
 * 0 - Enter, confirm	[V]	: Used to select menu items or make choices from a list
 * 1 - Escape, cancel	[X]	: Used to exit a (sub)menu or cancel the current action
 * 2 - Left				[<]	: Used to move left, e.g. to select a digit
 * 3 - Right			[>]	: Used to move right, e.g. to select a digit
 *
 * The rotary encoder (ENCA, ENCB) controls an up/down counter connected to some field. 
 * It may be that the encoder has a bushbutton as well, this can be connected to GP4.
 *     ___     ___
 * ___|   |___|   |___  A
 *   ___     ___     _
 * _|   |___|   |___|   B
 *
 * Encoder channel A triggers on falling edge. 
 * Depending on B level, count is incremented or decremented.
 * 
 * The PTT is connected to GP_PTT_IN connects to Microphone PTT switch (active low).
 * A separate PTT output (GP_PTT_OUT) is used to signal other system components (active high).
 *
 *
 * *** Display layout ***
 *
 * TFT 320x240, divided in 4 areas:
 * +--------------------------+
 * | v USB       [||||||||||] | ---> Rx/Tx, Modulation, S-meter
 * | >  0dB   PTT   Slow      | ---> Display main settings
 * | +----------------------+ |
 * | |   1 4 0 7 4 . 0   kHz| | ---> Frequency of carrier
 * | +----------------------+ |
 * |                          | \
 * |                          |  |-> Three menu lines: RF gain, Vox, AGC settings, etc.
 * |                          | / 
 * |    [V]  [<]  [>]  [X]    | ---> Button labels (Accept, Left, Right, Cancel)
 * +--------------------------+
 *
 * In the hmi TUNE state only tuning is possible: 
 *   Left '<' and Right '>' buttons to select digit, active digit is highlighted
 *   Encoder to change value, 
 *   Accept 'V' button to commit change.
 *
 * Use Cancel 'X' button to enter the hmi MENU state for parameter settings.
 * In parameter settings:
 *   Encoder to change parameter value
 *   Accept to accept the shown value
 *   Left/Right to change parameter (if not accepted first, new value is discarded)
 *   Cancel to exit parameter settings
 *
 * Parameter	Values							
 * ------------------------------------------
 * Mode:		USB, LSB, AM, CW				
 * AGC:			Fast, Slow, Off					
 * Pre:			+10dB, 0dB, -10dB, -20dB, -30dB	
 * Vox:			NoVOX, Low, Medium, High		
 *
 * --to be extended--
 */
#include <stdio.h>
#include <string.h>
#include "pico/stdlib.h"
#include "hardware/timer.h"
#include "hardware/clocks.h"
#include "hardware/gpio.h"

#include "uSDR.h"
#include "lcd.h"
#include "hmi.h"
#include "dsp.h"
#include "si5351.h"
#include "relay.h"

/*
 * Some macros
 */
#ifndef MIN
#define MIN(x, y)        ((x)<(y)?(x):(y))  // Get min value
#endif
#ifndef MAX
#define MAX(x, y)        ((x)>(y)?(x):(y))  // Get max value
#endif


/*
 * GPIO masks
 */
#define GP_MASK_IN	((1<<GP_ENC_A)|(1<<GP_ENC_B)|(1<<GP_BTN_0)|(1<<GP_BTN_1)|(1<<GP_BTN_2)|(1<<GP_BTN_3))
#define GP_MASK_OUT	(1<<GP_PTT_OUT)

/*
 * IRQ event flags
 */
#define GPIO_IRQ_ALL		(GPIO_IRQ_LEVEL_LOW|GPIO_IRQ_LEVEL_HIGH|GPIO_IRQ_EDGE_FALL|GPIO_IRQ_EDGE_RISE)
#define GPIO_IRQ_EDGE_ALL	(GPIO_IRQ_EDGE_FALL|GPIO_IRQ_EDGE_RISE)


/*********************************************************************************************************************/
/*** HMI control logic - Finite State Machine                                                                      ***/
/*********************************************************************************************************************/

/*
 * Events are generated by the different buttons and rotary encoder.
 * Depending on HMI state the event leads to a certain action.
 * 
 * The FSM is a 2 dimensional array indexed with state and event.
 * Each element contains a function call for changing content and a pointer to the next state.
 * The function arranges all parameters for that specific state.
 *
 * Using an FSM gives more control over the HMI behavour than specifc coding.
 */

// HMI State definitions
#define HMI_S_TUN			0
#define HMI_S_MOD			1
#define HMI_S_AGC			2
#define HMI_S_PRE			3
#define HMI_S_VOX			4
#define HMI_NSTATES			5

// HMI Event definitions
#define HMI_E_INC			0
#define HMI_E_DEC			1
#define HMI_E_ACC			2
#define HMI_E_LFT			3
#define HMI_E_RGT			4
#define HMI_E_CAN			5
#define HMI_NEVENTS			6

// Define FSM element
typedef struct
{
	void (*f)(int event);													// State/event function call
	int next_state;															// Next state in FSM
} fsm_t;

int hmi_event, hmi_state;													// Last event and state

int   hmi_digit_i, hmi_digit_b;												// Active tune digit and backup
int   hmi_i_mod, hmi_b_mod;													// MOD menu indexand backup
int   hmi_i_agc, hmi_b_agc;													// AGC menu index and backup
int   hmi_i_pre, hmi_b_pre;													// PRE menu index and backup
int   hmi_i_vox, hmi_b_vox;													// VOX menu index and backup


// FSM : No operation
void hmi_nop(int event){};


// FSM : Handle events when in TUN state
uint32_t hmi_freq;															// Frequency from Tune state
int		 hmi_b_bpf;															// Bandpass filter backup
int      hmi_s_bpf[5] = {REL_LPF2, REL_BPF6, REL_BPF12, REL_BPF24, REL_BPF40};
uint32_t hmi_step[6] = {10000000, 1000000, 100000, 10000, 1000, 100};		// Frequency digit increments
#define HMI_MAXFREQ		30000000
#define HMI_MINFREQ		     100
#define HMI_MULFREQ            1											// Factor between HMI and VFO frequency
void hmi_tun(int evt)
{
	if (evt == HMI_E_CAN)													// Leave TUNE mode
	{
		hmi_digit_b = hmi_digit_i;											// Store tuning digit
		hmi_digit_i = -1;
		hmi_i_mod = hmi_b_mod;												// Restore backup values
		hmi_i_pre = hmi_b_pre;
		hmi_i_agc = hmi_b_agc;
		hmi_i_vox = hmi_b_vox;
		return;
	}
		
	switch (evt)
	{
	case HMI_E_INC:
		if (hmi_freq < (HMI_MAXFREQ - hmi_step[hmi_digit_i]))				// Boundary check
			hmi_freq += hmi_step[hmi_digit_i];								// Increment selected digit
		break;
	case HMI_E_DEC:	
		if (hmi_freq > (HMI_MINFREQ + hmi_step[hmi_digit_i]))				// Boundary check
			hmi_freq -= hmi_step[hmi_digit_i];								// Decrement selected digit
		break;
	case HMI_E_RGT:
		hmi_digit_i = (hmi_digit_i<5)?hmi_digit_i+1:5;						// Digit to the right
		break;
	case HMI_E_LFT:
		hmi_digit_i = (hmi_digit_i>0)?hmi_digit_i-1:0;						// Digit to the left
		break;
	}
};


// FSM : Handle events when in MOD state
#define HMI_NMOD	4
char* hmi_d_mod[HMI_NMOD] = {"USB","LSB","AM ","CW "};						// MOD display strings
int   hmi_s_mod[HMI_NMOD] = {MODE_USB, MODE_LSB, MODE_AM, MODE_CW};			// MOD target setting in dsp.c
void hmi_mod(int evt)
{
	switch (evt)
	{
	case HMI_E_ACC:
		hmi_b_mod = hmi_i_mod;												// Store value in backup
		dsp_setmode(hmi_s_mod[hmi_b_mod]);									//   and acivate.
		break;
	case HMI_E_CAN:
		hmi_digit_i = hmi_digit_b;											// Leave MENU mode, restore tune digit
	case HMI_E_RGT:
	case HMI_E_LFT:
		hmi_i_mod = hmi_b_mod;												// Restore backup value
		break;
	case HMI_E_INC:
		if (hmi_i_mod<HMI_NMOD-1) hmi_i_mod++;
		break;
	case HMI_E_DEC:
		if (hmi_i_mod>0) hmi_i_mod--;
		break;
	}	
};


// FSM : Handle events when in AGC state
#define HMI_NAGC	3
char* hmi_d_agc[HMI_NAGC] = {"None","Slow","Fast"};							// AGC display strings
int   hmi_s_agc[HMI_NAGC] = {AGC_NONE, AGC_SLOW, AGC_FAST};					// AGC target setting in dsp.c
void hmi_agc(int evt)
{
	switch (evt)
	{
	case HMI_E_ACC:
		hmi_b_agc = hmi_i_agc;												// Store value in backup
		dsp_setagc(hmi_s_agc[hmi_b_agc]);									//   and activate setting.
		break;
	case HMI_E_CAN:
		hmi_digit_i = hmi_digit_b;											// Leave MENU mode, restore tune digit
	case HMI_E_RGT:
	case HMI_E_LFT:
		hmi_i_agc = hmi_b_agc;												// Restore backup value
		break;
	case HMI_E_INC:
		if (hmi_i_agc<HMI_NAGC-1) hmi_i_agc++;
		break;
	case HMI_E_DEC:
		if (hmi_i_agc>0) hmi_i_agc--;
		break;
	}	
};


// FSM : Handle events when in PRE state
#define HMI_NPRE	5
char* hmi_d_pre[HMI_NPRE] = {"-30dB","-20dB","-10dB","  0dB","+10dB"};						// PRE level display strings
int   hmi_s_pre[HMI_NPRE] = {REL_ATT_30, REL_ATT_20, REL_ATT_10, REL_ATT_00, REL_PRE_10};	// PRE target setting in dsp.c
void hmi_pre(int evt)
{
	switch (evt)
	{
	case HMI_E_ACC:
		hmi_b_pre = hmi_i_pre;												// Exit with change: store value in backup
		relay_setattn(hmi_s_pre[hmi_b_pre]);								//   and activate.
		break;
	case HMI_E_CAN:
		hmi_digit_i = hmi_digit_b;											// Leave MENU mode, restore tune digit
	case HMI_E_RGT:
	case HMI_E_LFT:
		hmi_i_pre = hmi_b_pre;												// Exit without change: restore backup value
		break;
	case HMI_E_INC:
		if (hmi_i_pre<HMI_NPRE-1) hmi_i_pre++;
		break;
	case HMI_E_DEC:
		if (hmi_i_pre>0) hmi_i_pre--;
		break;
	}	
};


// FSM : Handle events when in VOX state
#define HMI_NVOX	4
char* hmi_d_vox[HMI_NVOX] = {"None","Low","Medium","High"};			        // VOX level display strings
int   hmi_s_vox[HMI_NVOX] = {VOX_OFF, VOX_LOW, VOX_MEDIUM, VOX_HIGH};		// VOX target setting in dsp.c
void  hmi_vox(int evt)
{
	switch (evt)
	{
	case HMI_E_ACC:
		hmi_b_vox = hmi_i_vox;												// Exit with change: store value in backup
		dsp_setvox(hmi_s_vox[hmi_b_vox]);									//   and activate.
		break;
	case HMI_E_CAN:
		hmi_digit_i = hmi_digit_b;											// Leave MENU mode, restore tune digit
	case HMI_E_RGT:
	case HMI_E_LFT:
		hmi_i_vox = hmi_b_vox;												// Exit without change: restore backup value
		break;
	case HMI_E_INC:
		if (hmi_i_vox<HMI_NVOX-1) hmi_i_vox++;
		break;
	case HMI_E_DEC:
		if (hmi_i_vox>0) hmi_i_vox--;
		break;
	}	
};


// Statemachine definition
fsm_t hmi_fsm[HMI_NEVENTS][HMI_NSTATES] = 
{
/*       {       TUN       },{      MOD        },{      AGC        },{      PRE        },{       VOX       } */
/*INC*/	{{hmi_tun,HMI_S_TUN},{hmi_mod,HMI_S_MOD},{hmi_agc,HMI_S_AGC},{hmi_pre,HMI_S_PRE},{hmi_vox,HMI_S_VOX}},
/*DEC*/	{{hmi_tun,HMI_S_TUN},{hmi_mod,HMI_S_MOD},{hmi_agc,HMI_S_AGC},{hmi_pre,HMI_S_PRE},{hmi_vox,HMI_S_VOX}},
/*ACC*/	{{hmi_tun,HMI_S_TUN},{hmi_mod,HMI_S_MOD},{hmi_agc,HMI_S_AGC},{hmi_pre,HMI_S_PRE},{hmi_vox,HMI_S_VOX}},
/*LFT*/	{{hmi_tun,HMI_S_TUN},{hmi_mod,HMI_S_VOX},{hmi_agc,HMI_S_MOD},{hmi_pre,HMI_S_AGC},{hmi_vox,HMI_S_PRE}},
/*RGT*/	{{hmi_tun,HMI_S_TUN},{hmi_mod,HMI_S_AGC},{hmi_agc,HMI_S_PRE},{hmi_pre,HMI_S_VOX},{hmi_vox,HMI_S_MOD}},
/*CAN*/	{{hmi_tun,HMI_S_MOD},{hmi_mod,HMI_S_TUN},{hmi_agc,HMI_S_TUN},{hmi_pre,HMI_S_TUN},{hmi_vox,HMI_S_TUN}}
};


// Determine event and invoke the HMI state machine
uint32_t callcount;
void hmi_callback(uint gpio, uint32_t events)
{
	callcount++;
	// Determine the HMI event
	if (!((1<<gpio)&GP_MASK_IN)) return;									// Exit if not HMI control
	if (!(events&GPIO_IRQ_EDGE_FALL)) return;								// Exit if not falling edge
	switch (gpio)
	{
	case GP_ENC_A:															// Encoder
		hmi_event = gpio_get(GP_ENC_B)?HMI_E_DEC:HMI_E_INC;					// Increment when low, decrement otherwise
		break;
	case GP_BTN_3:															// Enter
		hmi_event = HMI_E_ACC;
		break;
	case GP_BTN_2:															// Left
		hmi_event = HMI_E_LFT;
		break;
	case GP_BTN_1:															// Right
		hmi_event = HMI_E_RGT;
		break;
	case GP_BTN_0:															// Cancel
		hmi_event = HMI_E_CAN;
		break;
	}
	
	// Invoke HMI State Machine
	hmi_fsm[hmi_event][hmi_state].f(hmi_event);
	hmi_state = hmi_fsm[hmi_event][hmi_state].next_state;
}


/*********************************************************************************************************************/
/*** Prepare display layout, printing areas and buttons                                                            ***/
/*********************************************************************************************************************/

/* 
 * Left and right margins : 10 pix
 * Top lines   : 72 rows,   0 -  71,	max 2 lines of 32 pix (4, 36) or 24 pix (8, 40)
 * Freq window : 58 rows,  72 - 129,	max symbol height 50 pix (76)
 * Menu window : 76 rows, 130 - 205,	max 3 lines of 24 pix (132, 156, 180)
 * Button row  : 34 rows, 206 - 239,	max symbol height 32 pix
 */
#define HMI_BGND	BGNDCOLOR
#define HMI_TEXT	LGRAY
#define HMI_HIGH	LBLUE
#define HMI_FREQ	LGREEN
#define HMI_BUTT	WHITE

// Initialize overall display layout
void hmi_layout()
{
	sFONT *sym = &FontSYMs;
	
	// Initialize display layout
	lcd_clear(   0,  0, LCD_WIDTH, LCD_HEIGHT, HMI_BGND);									// Paint display
	lcd_clear(  15,  6, 94, 27, BLACK);														// Mode window
	lcd_clear( 115,  6, 94, 27, BLACK);														// Pre-amp window
	lcd_clear( 215,  6, 90, 27, BLACK);														// S-meter window
	lcd_clear(  15, 39, 94, 27, BLACK);														// 
	lcd_clear( 115, 39, 94, 27, BLACK);														// 
	lcd_clear( 215, 39, 90, 27, BLACK);														// 
	lcd_clear(  15, 72, LCD_WIDTH-30, 58, BLACK);											// Freq window

	// Paint 4 Buttons
	lcd_clear( 32, 216, 62, 23, BLACK); lcd_putxy( 56, 219, 'S', sym, HMI_BUTT, BLACK);		// Enter
	lcd_clear( 98, 216, 62, 23, BLACK); lcd_putxy(122, 219, '?', sym, HMI_BUTT, BLACK);		// Left
	lcd_clear(164, 216, 62, 23, BLACK); lcd_putxy(188, 219, 'T', sym, HMI_BUTT, BLACK);		// Right
	lcd_clear(230, 216, 62, 23, BLACK); lcd_putxy(254, 219, 'r', sym, HMI_BUTT, BLACK);		// Escape
}


// Print top line, font Arial Rounded 16x24
void hmi_topline()
{
	sFONT *sym = &FontSYMs;												// 16x16
	sFONT *fs = &FontAR;												// 16x24
	int sval;
	
	// Tx or Rx symbol & Mode
	lcd_putxy  ( 22, 12, (tx_enabled?'O':'P'), sym, ORANGE, BLACK);
	lcd_writexy( 48,  8, hmi_d_mod[hmi_b_mod], fs, HMI_TEXT, BLACK);
	
	// Current Rx pre-amp setting
	lcd_writexy( 120, 8, hmi_d_pre[hmi_b_pre], fs, HMI_TEXT, BLACK);
	
	// S-Meter
	sval = get_sval();
	lcd_clear( 222, 11, 4, 16, (sval> 0?LBLUE:HMI_BGND));
	lcd_clear( 228, 11, 4, 16, (sval> 1?LBLUE:HMI_BGND));
	lcd_clear( 234, 11, 4, 16, (sval> 2?LBLUE:HMI_BGND));
	lcd_clear( 240, 11, 4, 16, (sval> 3?LGREEN:HMI_BGND));
	lcd_clear( 246, 11, 4, 16, (sval> 4?LGREEN:HMI_BGND));
	lcd_clear( 252, 11, 4, 16, (sval> 5?LGREEN:HMI_BGND));
	lcd_clear( 258, 11, 4, 16, (sval> 6?YELLOW:HMI_BGND));
	lcd_clear( 264, 11, 4, 16, (sval> 7?YELLOW:HMI_BGND));
	lcd_clear( 270, 11, 4, 16, (sval> 8?YELLOW:HMI_BGND));
	lcd_clear( 276, 11, 4, 16, (sval>90?ORANGE:HMI_BGND));
	lcd_clear( 282, 11, 4, 16, (sval>91?ORANGE:HMI_BGND));
	lcd_clear( 288, 11, 4, 16, (sval>92?ORANGE:HMI_BGND));
	lcd_clear( 294, 11, 4, 16, (sval>93?ORANGE:HMI_BGND));
	
	// Second topline
}


// Print frequency window, 1 row 7 Segment 32x50
// Highlight digit only when in TUNE mode
void hmi_frequency(double freq, int dig)
{
	sFONT *f7 = &Font7SPP;
	sFONT *fb = &FontGR;
	char s[32];
	int i;
	
	sprintf(s,"%7.1f",(double)freq/1000.0);									// Format is important: 12345.6
	s[7] = 0;																// Terminate to be sure
	for(i=0; i<7; i++) if (s[i]==0x20) s[i] = 0x2f;							// Replace spaces with correct font char
	for(i=0; i<5; i++) 														// Leading 5 digits
	{
		if (hmi_digit_i==i)
			lcd_putxy( 20+i*32,76,s[i], f7, HMI_HIGH, BLACK);
		else
			lcd_putxy( 20+i*32,76,s[i], f7, HMI_FREQ, BLACK);
	}
	lcd_putxy( 20+5*32,76,s[i++], f7, HMI_FREQ, BLACK);						// Decimal point
	if (hmi_digit_i==5)														// Final digit
		lcd_putxy( 20+6*32,76,s[6], f7, HMI_HIGH, BLACK);
	else
		lcd_putxy( 20+6*32,76,s[6], f7, HMI_FREQ, BLACK);
	lcd_writexy(250,96,"kHz", fb, HMI_FREQ, BLACK);							// Units
}


// Print menu area, 3 rows Arial Rounded 16x24
void hmi_menu()
{
	sFONT *fs = &FontAR;													// 16x24
	char s[18];																// Max 17 characters of 16 pix width
	
	// Prints current menu selection for the active parameter
	// lcd_clear( 0, 130, LCD_WIDTH, 76, HMI_BGND);
	s[17] = 0;																// Terminate string
	switch (hmi_state)
	{
		case HMI_S_TUN:
			lcd_writexy(  20, 180 ,"                 " , fs, HMI_TEXT, HMI_BGND);
			break;
		case HMI_S_MOD:
			lcd_writexy(  20, 180 ,"Mode: " , fs, HMI_TEXT, HMI_BGND);		// 6 leading characters
			sprintf(s, "%-11.11s", hmi_d_mod[hmi_i_mod]);					// Left aligned, field width 11, max chars 11
			lcd_writexy( 20+6*16, 180 ,s , fs, HMI_HIGH, HMI_BGND);
			break;
		case HMI_S_AGC:
			lcd_writexy(  20, 180 ,"AGC: " , fs, HMI_TEXT, HMI_BGND);		// 5 leading characters
			sprintf(s, "%-12.12s", hmi_d_agc[hmi_i_agc]);					// Left aligned, field width 12, max chars 12
			lcd_writexy( 20+5*16, 180 ,s , fs, HMI_HIGH, HMI_BGND);
			break;
		case HMI_S_PRE:
			lcd_writexy( 20, 180 ,"Gain: " , fs, HMI_TEXT, HMI_BGND);		// 6 leading characters
			sprintf(s, "%-11.11s", hmi_d_pre[hmi_i_pre]);					// Left aligned, field width 11, max chars 11
			lcd_writexy( 20+6*16, 180 ,s , fs, HMI_HIGH, HMI_BGND);
			break;
		case HMI_S_VOX:
			lcd_writexy( 20, 180 ,"Vox: " , fs, HMI_TEXT, HMI_BGND);		// 5 leading characters
			sprintf(s, "%-12.12s", hmi_d_vox[hmi_i_vox]);					// Left aligned, field width 12, max chars 12
			lcd_writexy( 20+5*16, 180 ,s , fs, HMI_HIGH, HMI_BGND);
			break;
	}
	

}


/*********************************************************************************************************************/
/*** HMI evaluation routine                                                                                        ***/
/*********************************************************************************************************************/

/*
 * This core routine is called on a regular basis from the main loop.
 * - Test PTT state
 * - Redraw the display, representing the current state.
 * - If a parameter was changed by HMI, activate it in system
 */
#define PTT_DEBOUNCE	3													// Nr of cycles for debounce
int ptt_state;																// Debounce counter
bool ptt_active;															// Resulting state
void hmi_evaluate(void)
{
	int hmi_i_bpf;

	// PTT detect and debounce
	if (gpio_get(GP_PTT_IN))												// Get PTT level
	{
		if (ptt_state<PTT_DEBOUNCE)											// Increment debounce counter when high
			ptt_state++;
	}
	else 
	{
		if (ptt_state>0)													// Decrement debounce counter when low
			ptt_state--;
	}
	if (ptt_state == PTT_DEBOUNCE)											// Reset PTT when debounced level high
		ptt_active = false;
	if (ptt_state == 0)														// Set PTT active when debounced level low
		ptt_active = true;

	// Redraw display, assuming layout is not changed
	hmi_topline( );
	hmi_frequency( hmi_freq, hmi_digit_i);
	hmi_menu( );
	
	// Update frequency corresponding to latest entered values
	if (0<si_evaluate(0, HMI_MULFREQ*(hmi_freq-FC_OFFSET)))					// See if VFO was updated
	{
		if      (hmi_freq < 2500000UL)	hmi_i_bpf = 0;						// Check bandfilter setting
		else if (hmi_freq < 6000000UL)	hmi_i_bpf = 1;
		else if (hmi_freq < 12000000UL) hmi_i_bpf = 2;
		else if (hmi_freq < 24000000UL) hmi_i_bpf = 3;
		else 							hmi_i_bpf = 4;
		if (hmi_i_bpf != hmi_b_bpf)											// Force update when band changed
		{
			hmi_b_bpf = hmi_i_bpf;											// Save setting in backup
			relay_setband(hmi_s_bpf[hmi_b_bpf]);							//   and activate.
		}
	}
}



/*
 * Initialize the User interface
 */
void hmi_init(void)
{
	/*
	 * Notes on using GPIO interrupts: 
	 * The callback handles interrupts for all GPIOs with IRQ enabled.
	 * Level interrupts don't seem to work properly.
	 * For debouncing, the GPIO pins should be pulled-up and connected to gnd with 100nF.
	 * PTT has separate debouncing logic
	 */
	 
	// Init output GPIOs
	gpio_init_mask(GP_MASK_OUT);
	gpio_set_dir_out_masked(GP_MASK_OUT);
	
	// Init input GPIOs
	gpio_init_mask(GP_MASK_IN|GP_PTT_IN);
	gpio_set_dir_in_masked(GP_MASK_IN|GP_PTT_IN);
	
	// Enable pull-ups
	gpio_pull_up(GP_ENC_A);
	gpio_pull_up(GP_ENC_B);
	gpio_pull_up(GP_BTN_0);
	gpio_pull_up(GP_BTN_1);
	gpio_pull_up(GP_BTN_2);
	gpio_pull_up(GP_BTN_3);
	gpio_pull_up(GP_PTT_IN);
	
	// Enable interrupt on edge detected
	gpio_set_irq_enabled(GP_ENC_A, GPIO_IRQ_EDGE_ALL, true);
	gpio_set_irq_enabled(GP_BTN_0, GPIO_IRQ_EDGE_ALL, true);
	gpio_set_irq_enabled(GP_BTN_1, GPIO_IRQ_EDGE_ALL, true);
	gpio_set_irq_enabled(GP_BTN_2, GPIO_IRQ_EDGE_ALL, true);
	gpio_set_irq_enabled(GP_BTN_3, GPIO_IRQ_EDGE_ALL, true);
	
	// PTT will be polled, no IRQ
	//gpio_set_irq_enabled(GP_PTT_IN, GPIO_IRQ_EDGE_ALL, false);

	// Install callback, one function for all GPIOs, and enable interrupt line
	gpio_set_irq_enabled_with_callback(GP_ENC_A, GPIO_IRQ_EDGE_ALL, true, hmi_callback);
		
	// Initialize frequency
	hmi_state = HMI_S_TUN;
	hmi_digit_i = 4;														// TUNE state: kHz active digit 
	hmi_freq  = 7074000UL;													// Initial frequency
	hmi_b_bpf = REL_BPF12;													// Initial bandpass filter selection

	si_setphase(0, PH270);													// Set phase to 270deg (depends on mixer type)
	si_evaluate(0, HMI_MULFREQ*(hmi_freq-FC_OFFSET));						// Set freq to 7074 kHz (depends on mixer type)
	
	// PTT_IN debounce
	ptt_state  = PTT_DEBOUNCE;
	ptt_active = false;
	
	// Initialize HMI indices
	hmi_b_mod = 0;															// USB
	hmi_b_pre = 3;															// 0dB
	hmi_b_agc = 1;															// Slow
	hmi_b_vox = 0;															// Off

	// Update uSDR settings according to HMI initialisation	
	dsp_setmode(hmi_s_mod[hmi_b_mod]);
	dsp_setvox(hmi_s_vox[hmi_b_vox]);
	dsp_setagc(hmi_s_agc[hmi_b_agc]);	
	relay_setattn(hmi_s_pre[hmi_b_pre]);
	relay_setband(hmi_s_bpf[hmi_b_bpf]);

	// Force HMI refresh
	hmi_layout();
}

